INSERT INTO Systems (SystemName, SystemLevel) values ("Barnard's Star",1);
INSERT INTO Systems (SystemName, SystemLevel) values ("Cheyenne",1);
INSERT INTO Systems (SystemName, SystemLevel) values ("Maheo",1);
INSERT INTO Systems (SystemName, SystemLevel) values ("Narion",1);
INSERT INTO Systems (SystemName, SystemLevel) values ("Sol",1);
INSERT INTO Systems (SystemName, SystemLevel) values ("Alpha Centauri",5);
INSERT INTO Systems (SystemName, SystemLevel) values ("Luyten's Star",5);
INSERT INTO Systems (SystemName, SystemLevel) values ("Procyon B",5);
INSERT INTO Systems (SystemName, SystemLevel) values ("Sirius",5);
INSERT INTO Systems (SystemName, SystemLevel) values ("Toliman",5);
INSERT INTO Systems (SystemName, SystemLevel) values ("Valo",5);
INSERT INTO Systems (SystemName, SystemLevel) values ("Volii",5);
INSERT INTO Systems (SystemName, SystemLevel) values ("Wolf",5);
INSERT INTO Systems (SystemName, SystemLevel) values ("Bessel",10);
INSERT INTO Systems (SystemName, SystemLevel) values ("Carinae",10);
INSERT INTO Systems (SystemName, SystemLevel) values ("Eta Cassiopeia",10);
INSERT INTO Systems (SystemName, SystemLevel) values ("Kapteyn's Star",10);
INSERT INTO Systems (SystemName, SystemLevel) values ("Olympus",10);
INSERT INTO Systems (SystemName, SystemLevel) values ("Piazzi",10);
INSERT INTO Systems (SystemName, SystemLevel) values ("Procyon A",10);
INSERT INTO Systems (SystemName, SystemLevel) values ("Tau Ceti",10);
INSERT INTO Systems (SystemName, SystemLevel) values ("The Pup",10);
INSERT INTO Systems (SystemName, SystemLevel) values ("Van Maanen's Star",10);
INSERT INTO Systems (SystemName, SystemLevel) values ("Altair",15);
INSERT INTO Systems (SystemName, SystemLevel) values ("Andromas",15);
INSERT INTO Systems (SystemName, SystemLevel) values ("Aranae",15);
INSERT INTO Systems (SystemName, SystemLevel) values ("Arcturus",15);
INSERT INTO Systems (SystemName, SystemLevel) values ("Muphrid",15);
INSERT INTO Systems (SystemName, SystemLevel) values ("Sagan",15);
INSERT INTO Systems (SystemName, SystemLevel) values ("Sakharov",15);
INSERT INTO Systems (SystemName, SystemLevel) values ("Beta Andraste",20);
INSERT INTO Systems (SystemName, SystemLevel) values ("Bradbury",20);
INSERT INTO Systems (SystemName, SystemLevel) values ("Eridani",20);
INSERT INTO Systems (SystemName, SystemLevel) values ("Guniibuu",20);
INSERT INTO Systems (SystemName, SystemLevel) values ("Indum",20);
INSERT INTO Systems (SystemName, SystemLevel) values ("Kryx",20);
INSERT INTO Systems (SystemName, SystemLevel) values ("McClure",20);
INSERT INTO Systems (SystemName, SystemLevel) values ("Oborum Prime",20);
INSERT INTO Systems (SystemName, SystemLevel) values ("Ursae Minoris",20);
INSERT INTO Systems (SystemName, SystemLevel) values ("Delta Pavonis",25);
INSERT INTO Systems (SystemName, SystemLevel) values ("Groombridge",25);
INSERT INTO Systems (SystemName, SystemLevel) values ("Kumasi",25);
INSERT INTO Systems (SystemName, SystemLevel) values ("Lunara",25);
INSERT INTO Systems (SystemName, SystemLevel) values ("Oborum Proxima",25);
INSERT INTO Systems (SystemName, SystemLevel) values ("Vega",25);
INSERT INTO Systems (SystemName, SystemLevel) values ("Alpha Andraste",30);
INSERT INTO Systems (SystemName, SystemLevel) values ("Copernicus",30);
INSERT INTO Systems (SystemName, SystemLevel) values ("Copernicus Minor",30);
INSERT INTO Systems (SystemName, SystemLevel) values ("Denebola",30);
INSERT INTO Systems (SystemName, SystemLevel) values ("Lantana",30);
INSERT INTO Systems (SystemName, SystemLevel) values ("Porrima",30);
INSERT INTO Systems (SystemName, SystemLevel) values ("Ursae Majoris",30);
INSERT INTO Systems (SystemName, SystemLevel) values ("Al-Battani",35);
INSERT INTO Systems (SystemName, SystemLevel) values ("Alpha Tirna",35);
INSERT INTO Systems (SystemName, SystemLevel) values ("Beta Tirna",35);
INSERT INTO Systems (SystemName, SystemLevel) values ("Bolivar",35);
INSERT INTO Systems (SystemName, SystemLevel) values ("Jaffa",35);
INSERT INTO Systems (SystemName, SystemLevel) values ("Nemeria",35);
INSERT INTO Systems (SystemName, SystemLevel) values ("Rivera",35);
INSERT INTO Systems (SystemName, SystemLevel) values ("Shoza",35);
INSERT INTO Systems (SystemName, SystemLevel) values ("Beta Ternion",40);
INSERT INTO Systems (SystemName, SystemLevel) values ("Freya",40);
INSERT INTO Systems (SystemName, SystemLevel) values ("Hyla",40);
INSERT INTO Systems (SystemName, SystemLevel) values ("Ixyll",40);
INSERT INTO Systems (SystemName, SystemLevel) values ("Khayyam",40);
INSERT INTO Systems (SystemName, SystemLevel) values ("Moloch",40);
INSERT INTO Systems (SystemName, SystemLevel) values ("Nikola",40);
INSERT INTO Systems (SystemName, SystemLevel) values ("Nirvana",40);
INSERT INTO Systems (SystemName, SystemLevel) values ("Rasalhague",40);
INSERT INTO Systems (SystemName, SystemLevel) values ("Alpha Marae",45);
INSERT INTO Systems (SystemName, SystemLevel) values ("Bara",45);
INSERT INTO Systems (SystemName, SystemLevel) values ("Beta Marae",45);
INSERT INTO Systems (SystemName, SystemLevel) values ("Linnaeus",45);
INSERT INTO Systems (SystemName, SystemLevel) values ("Ophion",45);
INSERT INTO Systems (SystemName, SystemLevel) values ("Rutherford",45);
INSERT INTO Systems (SystemName, SystemLevel) values ("Tidacha",45);
INSERT INTO Systems (SystemName, SystemLevel) values ("Alchiba",50);
INSERT INTO Systems (SystemName, SystemLevel) values ("Bannoc",50);
INSERT INTO Systems (SystemName, SystemLevel) values ("Bannoc Secondus",50);
INSERT INTO Systems (SystemName, SystemLevel) values ("Delta Vulpes",50);
INSERT INTO Systems (SystemName, SystemLevel) values ("Gamma Vulpes",50);
INSERT INTO Systems (SystemName, SystemLevel) values ("Xi Ophiuchi",50);
INSERT INTO Systems (SystemName, SystemLevel) values ("Zeta Ophiuchi",50);
INSERT INTO Systems (SystemName, SystemLevel) values ("Zosma",50);
INSERT INTO Systems (SystemName, SystemLevel) values ("Bel",55);
INSERT INTO Systems (SystemName, SystemLevel) values ("Feynman",55);
INSERT INTO Systems (SystemName, SystemLevel) values ("Heisenberg",55);
INSERT INTO Systems (SystemName, SystemLevel) values ("Leviathan",55);
INSERT INTO Systems (SystemName, SystemLevel) values ("Newton",55);
INSERT INTO Systems (SystemName, SystemLevel) values ("Nirah",55);
INSERT INTO Systems (SystemName, SystemLevel) values ("Serpentis",55);
INSERT INTO Systems (SystemName, SystemLevel) values ("Syrma",55);
INSERT INTO Systems (SystemName, SystemLevel) values ("Alpha Ternion",60);
INSERT INTO Systems (SystemName, SystemLevel) values ("Decaran",60);
INSERT INTO Systems (SystemName, SystemLevel) values ("Foucault",60);
INSERT INTO Systems (SystemName, SystemLevel) values ("Kang",60);
INSERT INTO Systems (SystemName, SystemLevel) values ("Maal",60);
INSERT INTO Systems (SystemName, SystemLevel) values ("Sparta",60);
INSERT INTO Systems (SystemName, SystemLevel) values ("Zelazny",60);
INSERT INTO Systems (SystemName, SystemLevel) values ("Charybdis",65);
INSERT INTO Systems (SystemName, SystemLevel) values ("Enlil",65);
INSERT INTO Systems (SystemName, SystemLevel) values ("Leonis",65);
INSERT INTO Systems (SystemName, SystemLevel) values ("Proxima Ternion",65);
INSERT INTO Systems (SystemName, SystemLevel) values ("Rana",65);
INSERT INTO Systems (SystemName, SystemLevel) values ("Schrodinger",65);
INSERT INTO Systems (SystemName, SystemLevel) values ("Algorab",70);
INSERT INTO Systems (SystemName, SystemLevel) values ("Bardeen",70);
INSERT INTO Systems (SystemName, SystemLevel) values ("Celebrai",70);
INSERT INTO Systems (SystemName, SystemLevel) values ("Marduk",70);
INSERT INTO Systems (SystemName, SystemLevel) values ("Pyraas",70);
INSERT INTO Systems (SystemName, SystemLevel) values ("Strix",70);
INSERT INTO Systems (SystemName, SystemLevel) values ("Verne",70);
INSERT INTO Systems (SystemName, SystemLevel) values ("Archimedes",75);
INSERT INTO Systems (SystemName, SystemLevel) values ("Bohr",75);
INSERT INTO Systems (SystemName, SystemLevel) values ("Fermi",75);
INSERT INTO Systems (SystemName, SystemLevel) values ("Hawking",75);
INSERT INTO Systems (SystemName, SystemLevel) values ("Huygens",75);
INSERT INTO Systems (SystemName, SystemLevel) values ("Katydid",75);
INSERT INTO Systems (SystemName, SystemLevel) values ("Masada",75);
INSERT INTO Systems (SystemName, SystemLevel) values ("Heinlein",45);